documentation:
  - changed-files:
      - all-globs-to-all-files: ['**/*.md']

github_actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'scripts/**']

go:
  - changed-files:
      - any-glob-to-any-file: ['**/*.go']

testing:
  - changed-files:
      - any-glob-to-any-file: ['integration/**', '**/*_test.go']

benchmarking:
  - changed-files:
      - any-glob-to-any-file: ['benchmark/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['**/go.mod', '**/go.sum']
