# https://golangci-lint.run/usage/configuration#config-file

linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - revive
    - vet
    - unused
    - misspell
  disable:
    - errcheck

issues:
  exclude-rules:
    - linters:
        - revive
      # Ignore unused parameter rule. It's not enforced by go and it can make it hard
      # to understand what the unused parameter was supposed to be used for.
      text: "unused-parameter:"

run:
  deadline: 4m
  skip-dirs:
    - docs
    - images
    - out
    - script
