# https://golangci-lint.run/usage/configuration#config-file
version: "2"
linters:
  enable:
    - copyloopvar
    - misspell
    - revive
    - staticcheck
    - unconvert
  settings:
    staticcheck:
      checks:
        - all
        # ST1003 is left out because it is a bit opinionated.
        - -ST1003
        # QF1008 discourages use of embedded field names,
        # which can sometimes clear up what certain fields
        # correspond to, especially in larger structs.
        - -QF1008
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        # Ignore unused parameter rule. It's not enforced by go and
        # it can make it hard to understand what the unused parameter
        # was supposed to be used for.
        text: 'unused-parameter:'
    paths:
      - docs
      - images
      - out
      - script
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs
      - images
      - out
      - script
      - third_party$
      - builtin$
      - examples$

run:
  timeout: 3m
