# https://golangci-lint.run/usage/configuration#config-file

linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - revive
    - vet
    - unused
    - misspell
  disable:
    - errcheck

run:
  deadline: 4m
  skip-dirs:
    - docs
    - images
    - out
    - script
