// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v09

import "strconv"

type CompressionAlgorithm int8

const (
	CompressionAlgorithmGzip CompressionAlgorithm = 1
)

var EnumNamesCompressionAlgorithm = map[CompressionAlgorithm]string{
	CompressionAlgorithmGzip: "Gzip",
}

var EnumValuesCompressionAlgorithm = map[string]CompressionAlgorithm{
	"Gzip": CompressionAlgorithmGzip,
}

func (v CompressionAlgorithm) String() string {
	if s, ok := EnumNamesCompressionAlgorithm[v]; ok {
		return s
	}
	return "CompressionAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
