// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ztoc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TOC struct {
	_tab flatbuffers.Table
}

func GetRootAsTOC(buf []byte, offset flatbuffers.UOffsetT) *TOC {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TOC{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTOC(buf []byte, offset flatbuffers.UOffsetT) *TOC {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TOC{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TOC) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TOC) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TOC) Metadata(obj *FileMetadata, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TOC) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TOCStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TOCAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metadata), 0)
}
func TOCStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TOCEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
