// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ztoc

import "strconv"

type CompressionAlgorithm int8

const (
	CompressionAlgorithmGzip         CompressionAlgorithm = 1
	CompressionAlgorithmUncompressed CompressionAlgorithm = 2
)

var EnumNamesCompressionAlgorithm = map[CompressionAlgorithm]string{
	CompressionAlgorithmGzip:         "Gzip",
	CompressionAlgorithmUncompressed: "Uncompressed",
}

var EnumValuesCompressionAlgorithm = map[string]CompressionAlgorithm{
	"Gzip":         CompressionAlgorithmGzip,
	"Uncompressed": CompressionAlgorithmUncompressed,
}

func (v CompressionAlgorithm) String() string {
	if s, ok := EnumNamesCompressionAlgorithm[v]; ok {
		return s
	}
	return "CompressionAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
