name: Visualize Benchmark

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes

permissions:
  contents: write
  deployments: write
      
jobs:
  benchmark:
    name: Run Benchmarks on PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: make
      - name: Run benchmark
        run: echo "Benchmarking..."
      # - run: make benchmarks-perf-test 

        
  update-benchmark-result:
      name: Update latest benchmark result
      needs: benchmark
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions/upload-artifact@v3
          with:
            name: benchmark-result
            path: ${{github.workspace}}/results.json

  # push-benchmark-result-gh-pages:
  #     name: Push benchmark result to Github-pages
  #     runs-on: ubuntu-20.04
  #     steps:
  #       - uses: actions/checkout@v3
  #         with:
  #           ref: main
  #       - uses: benchmark-action/github-action-benchmark@v1
  #         with:
  #           name: Soci Benchmark
  #           tool: 'customSmallerIsBetter'
  #           benchmark-data-dir-path: "dev/bench/perfTest"
  #           output-file-path: ${{github.workspace}}/results.json
  #           github-token: ${{ secrets.GITHUB_TOKEN }}
  #           auto-push: true
  #           # Show alert with commit comment on detecting possible performance regression
  #           alert-threshold: '200%'
  #           comment-on-alert: true
  #           fail-on-alert: true
  #       - name: Push benchmark result
  #         run: git push 'https://github.com/awslabs/soci-snapshotter.git' gh-pages:gh-pages

# $ {{github.workspace}}/benchmark/performanceTest/output/results.json