name: Visualize Benchmark and upload results

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes

permissions:
  contents: write
  deployments: write
      
jobs:
  benchmark:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20.6'
      - run: make
      - name: Run benchmark
        run: make benchmarks-perf-test 
      - name: Upload latest benchmark result
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: benchmark-result-artifact
          path: ${{github.workspace}}/benchmark/performanceTest/output/results.json
      
  download-and-convert-benchmark-result-to-visualization-data:
    runs-on: ubuntu-20.04
    needs: benchmark
    steps:
      - name: Checkout main branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download latest benchmark result
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: benchmark-result-artifact
          path: ${{github.workspace}}
      - name: Make temporary folder
        run: mkdir ${{github.workspace}}/current
      - name: Change permission of visualization-data-converter.sh
        run: chmod +x ${{github.workspace}}/scripts/visualization-data-converter.sh
      - name: Convert benchmark result to visualization data
        run: ${{github.workspace}}/scripts/visualization-data-converter.sh ${{github.workspace}}/results.json ${{github.workspace}}/current  
      - name: Build matrix of filepaths
        id: set-matrix
         # Create a JSON array with the file paths and store it in the 'files' output
        run: echo "files=$(find ${{github.workspace}}/current -type f -name '*.json' -printf '%p\n' | jq -R . | jq -cs .)" >> $GITHUB_OUTPUT
      - name: Upload visualization files as github artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: benchmark-gh-pages-artifact
          path: ${{github.workspace}}/current
    outputs:
      matrix: ${{ steps.set-matrix.outputs.files }}

  push-benchmark-result-gh-pages:
    name: Push benchmark result to Github-pages
    runs-on: ubuntu-20.04
    needs: download-and-convert-benchmark-result-to-visualization-data
    strategy:
      matrix:
        file: ${{ fromJson(needs.download-and-convert-benchmark-result-to-visualization-data.outputs.matrix) }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Create current folder
        run: mkdir ${{github.workspace}}/current

      - name: Download latest benchmark visualization files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: benchmark-gh-pages-artifact
          path: ${{github.workspace}}/current
      
      - name: Extract file names
        id: get_filename
        run: |
          # Get the filename without the path
          filename=$(basename "${{ matrix.file }}")
          # Remove the .json extension
          filename_without_extension="${filename%.json}"
          echo "filename=$filename_without_extension" >> $GITHUB_OUTPUT    

      - name: Run benchmark action
        uses: benchmark-action/github-action-benchmark@70405016b032d44f409e4b1b451c40215cbe2393 # v1.18.0
        with:
          name: Soci Benchmark
          tool: 'customSmallerIsBetter'
          benchmark-data-dir-path: "dev/benchmarks/performanceTest/${{ steps.get_filename.outputs.filename }}"
          output-file-path: ${{ matrix.file }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true