name: Regression test

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: Run Benchmarks on PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: make
      # - name: Run benchmark
      #   run: make benchmarks-perf-test
      # - run: cd benchmark/performanceTest && cat output/results.json
  generate_json_files:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - uses: actions/checkout@v3
      - name: Generate JSON files
        run: echo "sudo scripts/pre-process-results.sh"

  fetch_previous_json_files:
    runs-on: ubuntu-latest
    needs: generate_json_files
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Download previous artifact
        id: fetch_benchmark_files
        uses: actions/download-artifact@v3
        with:
          name: benchmark-result
          path: benchmark-result
        continue-on-error: true
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: benchmark-result