name: Update Benchmark Baseline


on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 */20 * *'

jobs:
    benchmark:
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout main branch
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              submodules: true
          - uses: actions/setup-go@v4
            with:
              go-version: '1.20.6'
          - run: make
          - name: Run benchmark
            run: make benchmarks-perf-test 
          - name: Upload latest benchmark result
            uses: actions/upload-artifact@v3
            with:
              name: benchmark-baseline-artifact
              path: ${{github.workspace}}/benchmark/performanceTest/output/results.json