name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - '.github/workflows/releases.yml'
      - 'scripts/**'
      - 'Makefile'

env:
  GO_VERSION: '1.25.11'

permissions:
  contents: write
  deployments: write

jobs:
  # Ensure all the correct artifacts are in the release branch
  # setup needs this on PR to test the release workflow on PR
  # and there's no easy way to skip all steps while allowing
  # setup workflow to run so just skip all the steps that can fail.
  check-release-branch-state:
    runs-on: ubuntu-22.04

    env:
      CHECKOUT_REF: '' # Filled in first steps
      RELEASE_TAG: '' # Filled in first steps

    steps:
      - name: Set target branch as main for pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "CHECKOUT_REF=main" >> $GITHUB_ENV
          echo "RELEASE_TAG=v0.0.0" >> $GITHUB_ENV

      - name: Check provided tag is properly formatted for push
        if: github.event_name == 'push'
        run: |
          release_tag=${GITHUB_REF#refs/*/} # Strip down to raw tag name
          echo "${release_tag}" | grep -qP '^v[0-9]+\.[0-9]+\.[0-9]+$'
          echo "Got tag ${release_tag} from input"
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_ENV

          # Export commit sha
          echo "CHECKOUT_REF=${GITHUB_SHA}" >> $GITHUB_ENV

      - uses: actions/checkout@v7
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go-licenses
        run: go install github.com/google/go-licenses/v2@v2.0.1

      - name: Generate third party licenses file
        run: bash scripts/build-third-party-licenses.sh

      - name: Check diff is empty
        if: github.event_name == 'push'
        run: |
          git add THIRD_PARTY_LICENSES
          git diff HEAD --exit-code

      - name: Increment version in docs
        run: bash scripts/update-version-in-docs.sh ${{ env.RELEASE_TAG }}

      - name: Check diff is empty
        if: github.event_name == 'push'
        run: |
          git add docs/
          git diff HEAD --exit-code

  setup:
    # Only run this if either of the previous two are a success.
    # We still need this to run after the checks but don't need the checks on a PR.
    needs: check-release-branch-state
    uses: ./.github/workflows/setup.yml

  generate-artifacts:
    needs: setup
    runs-on: ${{ fromJSON(needs.setup.outputs.runner-labels)[matrix.os] }}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.available-runners) }}
    env:
      # Set during setup.
      RELEASE_TAG: ''
      DYNAMIC_BINARY_NAME: ''
      STATIC_BINARY_NAME: ''
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install static libraries on AL2 ARM instances
        if: matrix.os == 'al2-arm'
        run: dnf install glibc-static.aarch64 zlib-static.aarch64 -y
      - name: Export cleaned release tag
        run: |
          export release_tag=${GITHUB_REF#refs/*/} # Strip down to raw tag name
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_ENV
      - name: Create dummy environment for release
        if: github.event_name == 'pull_request'
        run: |
          touch THIRD_PARTY_LICENSES
          echo "RELEASE_TAG=v0.0.0" >> $GITHUB_ENV
      - name: Setup variables and release directories
        run: |
          export release_tag=${{ env.RELEASE_TAG }}
          export release_version=${release_tag/v/} # Remove v from tag name
          echo "DYNAMIC_BINARY_NAME=soci-snapshotter-${release_version}-linux-amd64.tar.gz" >> $GITHUB_ENV
          echo "STATIC_BINARY_NAME=soci-snapshotter-${release_version}-linux-amd64-static.tar.gz" >> $GITHUB_ENV

          mkdir release-${{ matrix.os }}
      - name: Create release binaries
        run: make RELEASE_TAG=${{ env.RELEASE_TAG }} release
      - uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.os }}
          path: release/
          if-no-files-found: error

    outputs:
      release_tag: ${{ env.RELEASE_TAG }}
      dynamic_binary_name: ${{ env.DYNAMIC_BINARY_NAME }}
      static_binary_name: ${{ env.STATIC_BINARY_NAME }}

  validate-artifacts:
    needs: [setup, generate-artifacts]
    runs-on: ${{ fromJSON(needs.setup.outputs.runner-labels)[matrix.os] }}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.available-runners) }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: artifacts-${{ matrix.os }}
          path: release/
      - run: bash scripts/verify-release-artifacts.sh ${{ needs.generate-artifacts.outputs.release_tag }}

  create-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: validate-artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          path: assets/
          pattern: artifacts-*
          merge-multiple: true
      - uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          generate_release_notes: false
          files: assets/*
