name: Update version in docs

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'New SOCI release tag'
        required: true
        type: string
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  release:
    types: ['released']
  pull_request:
    branches: ['main']
    paths:
      # Run workflow on changes to the workflow definition itself to spot check
      # the core version update functionality.
      - '.github/workflows/update-version-in-docs.yml'
      - 'scripts/update-version-in-docs.sh'
      # Run workflow on changes to the getting started guide to validate
      # changes to the documentation do not break the update workflow.
      - 'docs/getting-started.md'
      - 'docs/eks.md'
  # Run workflow on all pushes to a release branch
  push:
    branches: ['release/**']

jobs:
  test-update-version:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            docs/eks.md
            docs/getting-started.md
            scripts/update-version-in-docs.sh

      - name: Test update getting started version
        run: bash scripts/update-version-in-docs.sh --assert v0.0.0-${{ github.event.pull_request.number }}

  update-version:
    # Don't run this on GitHub action pushes as they are probably other automated changes that need to go thru
    if: github.event_name != 'pull_request' && (github.event_name != 'push' || github.event.head_commit.author.name != 'github-actions')
    runs-on: ubuntu-22.04

    env:
      TAG_NAME: '' # Set in steps
      TARGET_BRANCH: '' # Set in steps

    permissions:
      # Write permissions needed to create pull request.
      # Risk for pwn requests is mitigated by seperating jobs such that
      # workflows running with write permissions only use code from main.
      contents: write
      pull-requests: write

    steps:
      - name: Set vars for workflow dispatch/call
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        run: |
          # This will fail if tag is not in semver starting with v
          echo "${{ inputs.tag_name }}" | grep -qP '^v[0-9]+\.[0-9]+\.[0-9]+$'
          echo "Got tag ${{ inputs.tag_name }} from input"

          echo "TAG_NAME=${{ inputs.tag_name }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=release/$(echo ${{ inputs.tag_name }} | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - name: Set vars for release
        if: github.event_name == 'release'
        run: |
          # This will fail if tag is not in semver starting with v
          echo "${{ github.event.release.tag_name }}" | grep -qP '^v[0-9]+\.[0-9]+\.[0-9]+$'
          echo "Got tag ${{ github.event.release.tag_name }} from release"

          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=main" >> $GITHUB_ENV

      - name: Set vars for push
        if: github.event_name == 'push'
        run: |
          branch_name=${{ github.ref_name }}
          major_minor=${branch_name#*/}

          # curl GitHub API to get latest tag based on the branch that was pushed to
          # Increment patch ver, since push action implies we are updating an existing release branch
          latest_tag=$(curl -s https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases | grep "tag_name" | cut -d '"' -f 4 | grep ${major_minor} | head -n 1 | awk -F. -v OFS=. '{$NF += 1 ; print}')

          # Fallback if tag isn't found, assume major.minor.0
          if [ -z "$latest_tag" ]; then latest_tag="v${major_minor}.0"; fi

          # This will fail if tag is not in semver starting with v
          echo "${latest_tag}" | grep -qP '^v[0-9]+\.[0-9]+\.[0-9]+$'
          echo "Got latest tag ${latest_tag} from upstream"

          echo "TAG_NAME=${latest_tag}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v6
        with:
          ref: ${{ env.TARGET_BRANCH }}
          sparse-checkout: |
            docs/eks.md
            docs/getting-started.md
            scripts/update-version-in-docs.sh

      - name: Update getting started version
        run: bash scripts/update-version-in-docs.sh --verbose ${{ env.TAG_NAME }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'Update version in docs to ${{ env.TAG_NAME }}'
          commit-message: 'Update version in docs to ${{ env.TAG_NAME }}'
          body: |
            This change updates SOCI docs to point to ${{ env.TAG_NAME }}.

            This PR must be closed and reopened manually to trigger automated checks.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: easy-to-review, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "GitHub <no-reply@github.com>"
          signoff: true
          branch: 'create-pull-request/update-version-in-docs-to-${{ env.TAG_NAME }}'
          base: ${{ env.TARGET_BRANCH }}
          delete-branch: true
